name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/WhatTheHellDidIRoll.sln
    - name: Build
      run: dotnet build src/WhatTheHellDidIRoll.sln --no-restore -c Release
